services:
  movieapp:
    build: .
    image: movieapp
    container_name: movieapp
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    volumes:
      - ./movieapp:/app/www/movieapp
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
     - dbnet

networks:
  dbnet:
   driver: bridge

volumes:
  postgres-data:
