services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=mystoredb
      - POSTGRES_USER=superadmin
      - POSTGRES_PASSWORD=314748
      - POSTGRES_HOST=pgdb

    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data

volumes:
  pgdbdata: