services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
  db:
   image: postgres:13
   environment:
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   volumes:
     - postgres_data:/var/lib/postgressql/data/

volumes:
  postgres_data:
  static:
  media:
  
        
  
  