# Generated by Django 4.2.20 on 2025-04-02 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('reting', models.IntegerField()),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
