# Generated by Django 4.2.20 on 2025-03-30 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
    ]
