# Generated by Django 4.2.20 on 2025-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reting',
            field=models.IntegerField(max_length=1),
        ),
    ]
